### ISSUE TITLE
cannot set comfortZone: 0

### ISSUE THREAD

**Issue by leeoniya** [Pixabay/jQuery-autoGrowInput#1]
first, you've got quite a lot of excellent and truly lightweight plugins, thank you.

the falsy check here prevents `comfortZone: 0` from working:

https://github.com/Pixabay/jQuery-autoGrowInput/blob/master/jquery.auto-grow-input.js#L17

having a `0` default makes sense (and is what i want), but makes things tricky when combined with an _auto_ fallback. not sure how you want to handle this. i'd probably just add an explicit "auto" option and do:

``` js
comfortZone = o.comfortZone == "auto" ? parseInt(input.css('fontSize')) : o.comfortZone,
```

cheers!

**Comment by SimonSteinberger** [comment]
Does it work for you to use comfortzone: 1? That's 1px, which should hardly be noticeable. If not, it's easy to adapt the plugin. If you say it makes sense, we'll implement this.

**Comment by leeoniya** [comment]
1px would probably work, but it's a hack :)

perhaps a better option would be to have the plugin respect any explicitly provided value if `comfortZone` is specified by the user, so:

``` js
comfortZone = "comfortZone" in options ? options.comfortZone : parseInt(input.css('fontSize')) ,
```

i modified my local copy to default to `0`, but i now realize that your original intent is to default to 1 char width (indicated by a falsy/0 `comfortZone`), so the two variations are not quite compatible.

**Comment by SimonSteinberger** [comment]
I'll include this in a few minutes:

```
comfortZone = (options && 'comfortZone' in options) ? o.comfortZone : parseInt(input.css('fontSize'))
```

Otherwise an error is raised when no options are passed.

**Comment by leeoniya** [comment]
:+1:
