### ISSUE TITLE
Bumpy ride when the input has property `text-transform: uppercase`

### ISSUE THREAD

**Issue by razzpoker50** [Pixabay/jQuery-autoGrowInput#10]
@SimonSteinberger This is a great plugin.

But I feel there is a minor use case missing. When the underlying input has `text-transform:uppercase` set. The width of the actual input is slightly more than the `tester` width because of which I came across a bumpy input when the width is set.

To offset that I had to set the css property `textTransform: input.css('textTransform') ? input.css('textTransform') : '',` which seems to have solved the problem. (Don't even need the ternary operator though). 

Any thought from your side ?

**Comment by SimonSteinberger** [comment]
Sounds good :+1:
