### ISSUE TITLE
Textarea does not autogrow after ajax return

### ISSUE THREAD

**Issue by swamyuma** [Pixabay/jQuery-autoGrowInput#12]
I am using [typhead search](http://www.runningcoder.org/jquerytypeahead/) plugin in a field to get value from an ajax call. The string returned is quite long. I have specified this field to autogrow, but doesn't seem to work!

``` javascript
$('#id_items_2').autoGrowInput({minWidth: 100, maxWidth: 800, comfortZone: 90});
```

Any suggestions please?

**Comment by SimonSteinberger** [comment]
Try triggering the `input` and `keydown`events on the input field after the Ajax request. `$('input').trigger('input', 'keydown');` Could work. When the value was changed through JavaScript, autoGrow is not triggered.

**Comment by SimonSteinberger** [comment]
Oops, I just noticed, you're working with textareas. But this plugin is purely designed for working with text input fields. Textareas are a totally different thing. Try http://www.jacklmoore.com/autosize/ for your purpose.
