### ISSUE TITLE
Register at CDN to increase ease of deployment

### ISSUE THREAD

**Issue by holtkamp** [Pixabay/jQuery-autoGrowInput#13]
To stimulate adoption and increase ease of deployment during production, registration of the Javascript files at a CDN like http://www.cdnjs.com is useful.

**Comment by SimonSteinberger** [comment]
You can use https://rawgit.com/ to have any GitHub file served though MaxCDN's super fast global CDN.

**Comment by holtkamp** [comment]
Indeed, RawGit is an option indeed. However: https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions#i-need-guaranteed-100-uptime-should-i-use-cdnrawgitcom, I will try to register it at CDNJS. Using their auto-update mechanism, requires a tagged version though as suggested in: https://github.com/Pixabay/jQuery-autoGrowInput/issues/9
