### ISSUE TITLE
when the input value is ' ', on page load will throw error "Unable to get property 'type' of undefined or null reference"

### ISSUE THREAD

**Issue by showching** [Pixabay/jQuery-autoGrowInput#16]
The error is:

SCRIPT5007: Unable to get property 'type' of undefined or null reference
File: jquery.auto-grow-input.js, Line: 33, Column: 21

**Comment by SimonSteinberger** [comment]
The `check` function is triggered by `input` and `keydown` events, not on `load`. So, I don't see the issue here.

**Comment by antejan** [comment]
I have same issue and suggested change fixes it for me.
Initially there is check() call without event argument, and if input value is single space (" ") there's an error.
Made a simple codepen for demonstration https://codepen.io/antejan/pen/QrBNZW
