### ISSUE TITLE
When using JSDOM, prop returns undefined and eventually throws "Cannot call method 'replace' of undefined" 

### ISSUE THREAD

**Issue by jmca** [Pixabay/jQuery-autoGrowInput#5]
Regarding line 32:
`if (!val) val = input.prop('placeholder');`

Is there any reason why this is not using `input.attr`? When using JSDOM for unit testing `input.prop('placeholder');` returns `undefined` which causes an error of `Cannot call method 'replace' of undefined` on line 33: `span.html(val.replace(/&/...`.

While `input.attr('placeholder');` returns the correct placeholder. I think using the `attr` would technically be "correct" since `placeholder` is an attribute.

Better yet, assign a default value if placeholder is not defined :

```
if (!val) val = input.attr('placeholder') || '';
```

**Comment by SimonSteinberger** [comment]
You're right. It's not a big difference, but attr is the better choice. Thanks!
