### ISSUE TITLE
jQuery input:text selector ignores text based html5 inputs

### ISSUE THREAD

**Issue by eballeste** [Pixabay/jQuery-autoGrowInput#6]
``` javascript
this.filter('input:text').each(function(){...});
```

to

``` javascript
this.filter('input[type=text], input[type=email], input[type=search], input[type=password], input[type=tel]').each(function(){...});
```

**Comment by dangoodman** [comment]
Why do ever need that filter? We don't know what types of input will be introduced in further html specifications. There might be even custom html input-like tags, e.g. angular directives. It looks for me like it'd better to get rid of it at all.

**Comment by SimonSteinberger** [comment]
Agreed :+1: I also think it's the developer's responsibility to make sure the plugin is only applied to suitable input types.

**Comment by dangoodman** [comment]
Great, thanks!

**Comment by eballeste** [comment]
yeap, that works
