### ISSUE TITLE
Tag (stable) versions

### ISSUE THREAD

**Issue by holtkamp** [Pixabay/jQuery-autoGrowInput#9]
Your [changelog](https://github.com/Pixabay/jQuery-autoGrowInput#changelog) indicates that [versioning](http://semver.org) is applied. Would be nice if you can ['tag' these releases in GitHub](https://help.github.com/articles/creating-releases/) also, so dependency managers like Bower can be instructed to install stable versions for production purposes:  `"~1.0"`. 

Kudo's for the nice plugin btw ;)

**Comment by holtkamp** [comment]
Running an update of our dependency manager, caused https://github.com/Pixabay/jQuery-autoGrowInput/commit/c3ced59124395304dd6a0804258d16a5b6f43571 to be pulled in, since the master branch is used.

Which is not a problem as long as it works. But adopting tagged version would prevent pulling in possibly unstable PRs...

Can you consider tagging the releases allowing a little bit more control on which changes to pull in?

**Comment by SimonSteinberger** [comment]
It's a rather simple plugin and we wouldn't release any unstable/dev versions here.

**Comment by holtkamp** [comment]
ok, so maybe a single '1.0.0' to mark the current master branch as being stable? Just so dependency managers like bower / composer-asset-plugin can refer to it...

having it refer to "*" or "dev-master" generates both warnings in IDE's and is bad practice...

**Comment by holtkamp** [comment]
bump on this request?

**Comment by holtkamp** [comment]
Switched to https://github.com/westonganger/input-autogrow/releases which is inspired by this component and has adopted proper version tagging

Closing issue
